baseURL = 'https://blog.gordontillman.info/'
languageCode = 'en-us'
title = "Gordy's Blog"
theme = 'ananke'

[params]
subtitle = 'Yet another blogging experiment...'
author = 'Gordon Tillman'
description = 'A place to share ideas and commentary.'
mainSections = ["posts"]

[markup.goldmark.renderer]
unsafe = true
