#+TITLE: Mounting External Drives - Ubuntu 14.04 and Chrombook
#+DATE: 2015-01-08
#+SETUPFILE: ~/.emacs.d/octopress-setupfile.txt
#+JEKYLL_LAYOUT: post
#+JEKYLL_CATEGORIES: chromebook ubuntu
#+JEKYLL_PUBLISHED: true

OK, this post is part of my continuing experiments with an ASUS C200
Chromebook.  I have installed Ubuntu 14.04 using /crouton/.

I had created two partitions on a Micro SD Card, one as Fat32 (EsFat
actually) and the other as ext4.  

The FAT32 partion mounts at ~/media/removeable/share~ and the ext4
partition mounts at ~/media/removeable/gordy~.  I tried storing
various projects on the ext4 partition but when I tried to build from
that partition I would get a permissions error.


{{{more}}}

Long story short, it turns out that the the ChromeOS side is mountint
the ext4 partition with /noexec/ permissions.  That was causing all
the problems.  The solution turned out to be simple.  Just a single
command to remount the partition (issued from the Ubuntu side) does
the trick:

#+BEGIN_SRC sh
sudo mount -t ext4 -o remount,rw /dev/mmcblk1p1 /var/host/media/removable/gordy
#+END_SRC

So, in the above command:

- ~-t ext4~ is the type of the partition.  I had previously formatted
  it as ext4.
- ~-o remount,rw~ tells the system to remote the partion with
  read/write privileges
- ~/dev/mmcblk1p1~ is the path to the partition that needs to be
  mounted.  It will likely be different on your machine.  You can find
  out what your device path is by just typing ~mount~ with no
  arguments and grepping for the name of the volume.
- ~/var/host/media/removable/gordy~ is the mount point.  A careful
  reader will notice that this is different than what I wrote at the
  top of the post (~/media/removeable/gordy~).  Well as it turns out
  ~/media/removeable~ is a symbolic link to
  ~/var/host/media/removeable~ and if you try to mount to
  ~/media/removeable/gordy~ the mount command complains about trying
  to follow too many symbolic links.  Please note that this mount path
  will also be different on you machine, unless you named your
  partition "gordy" as well. :-)


Anyway, after remounting I am able to use my ext4 partition to hold
projects and be able to ~./configure~ and ~make~ out of directories on
the partition just fine.
